### ISSUE TITLE
New Chapter: Assessing Culture Fit

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-leaders-manual#11]
This is a proposed chapter from @jenkelchner and MaryJo Burchard.

**Comment by jenkelchner** [comment]
Sent you the draft with a section that needs to be completed - my brain went off into a few new things related to it and I have to wrangle the concept back in to this one little section :)

**Comment by semioticrobotic** [comment]
Love the new edits, @jenkelchner! I've left you a few comments in-document, but nothing too hefty (I hope!).
