### ISSUE TITLE
New Chapter: Transformation Beyond the Digital

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-leaders-manual#13]
This is a proposed chapter from @jenkelchner.

**Comment by jenkelchner** [comment]
@semioticrobotic do you need to me to merge those two articles and bridge them? OR, will you simply do a copy/paste with them?

**Comment by semioticrobotic** [comment]
If you could merge and bridge, that would be most helpful—that way, I know that they're massaged together in the way you'd like, and you've added whatever extra flourish you'd like during the first draft. Then you and I can work together during editing to refine, build, etc.

**Comment by jenkelchner** [comment]
@semioticrobotic bridged version sent to you!

**Comment by semioticrobotic** [comment]
Looking sharp, @jenkelchner!

**Comment by semioticrobotic** [comment]
- A general comment: There a lots of em dashes in this chapter, which dilutes their effectiveness. It’s worth taking another look at them to see if tweaks can be made.

- Page 144, paragraph 1: Here’s an instance where an em dash could be replaced by a comma. You could also break things up into two sentences.

- Page 144, paragraph 2: Consider something similar to what’s above for the em dash here.

- Page 144, paragraph 3: The em dash in the second sentence makes for a very long sentence, one that’s hard for the reader to quickly digest. Maybe break up into two sentences instead.

- Page 144, paragraph 4: Replace the colon after “said” with a simple comma since we’re not introducing a block quote.

- Page 144, final paragraph, block quote: AP lowercases “millennials”. Our style guide doesn’t address. It needs to be changed throughout the chapter unless a direct quote has it capitalized.

- Page 145, paragraph 1: Another em dash here. You could get a similar effect by beginning the sentence with the phrase that follows, using a comma and beginning with “the 2018 Deloitte…”.

- Page 145, paragraph 1: Is it supposed to be “The survey’s findings lead…” instead of “The survey’s finding lead”?

- Page 145, paragraph one: Who is “they” referring to in the final sentence? I think it’s the leaders, but it could be clearer.

- Page 145, bulleted list, first bullet: Replace the semicolon after “force” with a comma, and replace “up” with “it”. End the bullet with a period.

- Page 145, bulleted list, second bullet: Insert an “s” at the end of “comprise”. End the bullet with a period.

- Page 145, bulleted list, third bullet: End the bullet with a period.

- Page 145, final paragraph: Consider tweaking things so you don’t have two sentences using a colon so close to together (back to the same idea with the em dashes). 

- Page 146, paragraph 1: Consider reworking the first sentence to eliminate the em dash.

- Page 146, paragraph 1: I noticed the “st” in “21st” isn’t superscripted. Is that our style? I simply don’t know.

- Page 146, paragraph 2: Insert a period after “down”. Capitalize “in” inside the parentheses, and move the period outside of the parentheses inside so it follows “up”.

- Page 146, paragraph 3: Make it “this change” instead of “the changes” so things follow in number with references made in the previous paragraph.

- Page 146, paragraph 3: I’m split on this one and bring it up for your consideration. Should it be “that” instead of “who” after generation?

- Page 146, paragraph 3: Our style guide calls for us to drop the hyphen in “real time” since it’s used as a noun here.

- Page 146, paragraph 3: Another em dash. You could simply go with a comma, or you could break into two sentences, especially given the length of the part following the em dash.

- Page 146, paragraph 3: See the earlier comment about “changes” versus “change” on this page (four bullets above).

- Page 147, partial paragraph that begins the page: Another instance where we’ve got “changes” and where “change” might fit better with the chapter’s overall flow.

- Page 147, partial paragraph beginning the page: Another em dash.

- Page 147, partial paragraph beginning the page: I stumbled with the last sentence. How about “We can no longer expect to do business while under operations and rules for sailing while navigating a lake full of speedboats”? I’m not sure that’s any better though.

- Page 147, paragraph one: The final sentence is quite long. You could replace the semicolon with a period and have two sentences.

- Page 147, paragraph two: I have no idea what’s going on with the first sentence. The semicolon and commas have me at a loss.

- Page 147, paragraph two: AP doesn’t typically hyphenate -ly constructions.

- Page 147, partial paragraph at the end of the page: Another fun em dash

- Page 148, paragraph 2: It should be “require” instead of “requires” since we’re agreeing with “efforts”.

- Page 148, paragraph 3: Insert a comma between “models” and “and”.

- Page 148, paragraph 3: Another em dash. You could get a similar effect with “Digital transformation. Policy and regulation changes. New business models. All are tools, vehicles aiding the achievement of new ends or goals.” The periods for incomplete sentences add emphasis and draw extra attention to what’s being said. Plus, that way, I don’t have to be a pain and bring up the em dash in the following paragraph.

- Page 148, paragraph 5: Replace the colon with a comma after “example”. Lower case “you’ve”. 

- Page 148, paragraph 5: Another em dash, but I’ve dealt with it already in my comments two bullets above.

- Page 149, paragraph 2: You can do without “then” after “risk mitigation,”. 

- Page 149, paragraph 2: Same thing for after “voices,”. 

- Page 149, paragraph 2: It should be “its”, not “it’s”. 

- Page 150, paragraph 1: “Then” isn’t necessary after “leader”.

- Page 150, paragraph 2: Delete “change” after “drive”.

- Page 150, bio: Replace “who” with “that” after “organizations”.
