### ISSUE TITLE
New Chapter: "Owning Your Career" in an Open Organization

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-leaders-manual#19]
This is a proposed chapter from @LauraHilliger and @amatlack.

**Comment by amatlack** [comment]
@LauraHilliger and I are done with the first draft and are ready to move it to editorial

**Comment by semioticrobotic** [comment]
Like the new draft! I just posed one final question about something I can't quite visualize.

**Comment by semioticrobotic** [comment]
I realized I might have prematurely assumed you were both finished working on this. Any further edits from @amatlack and/or @LauraHilliger?

**Comment by amatlack** [comment]
@semioticrobotic I need to go through one more time! I heard the deadline is Tuesday. ;-)

**Comment by amatlack** [comment]
@semioticrobotic @LauraHilliger apologies for the holdup. I've made revisions to the latter half and am ready to sign off for editorial!

**Comment by semioticrobotic** [comment]
Really nice chapter, @LauraHilliger and @amatlack. I made only small tweaks to the final draft you sent (for style, primarily), and will work on getting this typeset in production. Thanks for you great work.
