### ISSUE TITLE
New Chapter: Introduction to the Second Edition

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-leaders-manual#22]
This book's unique introduction comes from @jenkelchner.

**Comment by jenkelchner** [comment]
@semioticrobotic do we have a rough date for draft? I want to make sure I put a deadline on my calendar.

**Comment by semioticrobotic** [comment]
No, but I suppose we should, shouldn't we?

All final drafts are due no mater than November 4. At that time we're in full-on typesetting and proofing mode. If you think you'll want to see _all_ final chapters before writing the introduction, then that's the best time to get started. But if you want to begin sketching something in advance, then any time is fine (working galley proofs are always available for download from this repository, too, so you can begin referencing materials if you'd like).
