### ISSUE TITLE
ePub format?

### ISSUE THREAD

**Issue by moltar** [open-organization-ambassadors/open-org-leaders-manual#25]
Any chance on releasing this as ePub also? PDF is good for printing, but not very friendly for readers. Thanks.

**Comment by semioticrobotic** [comment]
I agree completely, @moltar, that an ePub version would be extremely useful. At the moment, however, we don't have resources available to produce one. In the past, intrepid community members have used the resources in this repository to create and contribute their own. I will gladly review pull requests pertaining to this.

**Comment by moltar** [comment]
@semioticrobotic Thanks, Bryan. Do you have any pointers and/or examples of previous solutions that you've mentioned?

**Comment by semioticrobotic** [comment]
Absolutely, @moltar. You might [check out the repo](https://github.com/open-organization-ambassadors/catalyst-in-chief) for the now out-of-print _Catalyst-In-Chief_, which contains a community-produced ePub.

**Comment by coevolving** [comment]
On converting ODT to ePub (and to LaTeX), I can speak from experience.  The text will translate relatively easily.  What takes time is the recoding of images (I had created ODG as vector graphics), footnotes links, and citations to the reference list (that I had created in Zotero).  

I first converted ODT to LaTeX, using [Writer 2 LaTeX](http://writer2latex.sourceforge.net/).  Editing in TexStudio (leading a 670-page document, including a 390+ page appendix, 64 figures as PDF, 34 tables, 1051 footnotes) took me 2 months.

I then converted from ODT to ePub3 in Sigil (with figures as SVG).  This took 2 months.

You can see the results as an open access book, [_Open Innovation Learning: Theory building on open soucing while private sourcing_](http://openinnovationlearning.com/online/).  On that page, you'll see notes that ePub3 readers have not uniformly implemented the standard, so fidelity will depend on the reader software chosen.

**Comment by semioticrobotic** [comment]
Images in this book are minimal—though they are present. I do know that LibreOffice now offers native ePub export, but I haven't had time to experiment with it. Perhaps one way to begin addressing this might be to export the book's source as ePub and open the resulting file in Sigil to see what you've got?

**Comment by semioticrobotic** [comment]
We now offer an officially supported [ePub format](https://github.com/open-organization-ambassadors/open-org-leaders-manual/blob/master/open_org_leaders_manual_2_1_2.epub)!
