### ISSUE TITLE
Dejavu Sans font website link not correct

### ISSUE THREAD

**Issue by lg2011** [open-organization-ambassadors/open-org-leaders-manual#26]
The link to the Dejavu Sans website on page 8 of the book seems to be wrong. May be the link to https://dejavu-fonts.github.io/ would be appropriate instead.

**Comment by semioticrobotic** [comment]
Thanks very much for spotting this. I'll address this bug when we issue updates to this and other books (as they all contain the wrong link!).

**Comment by semioticrobotic** [comment]
This has been fixed in the latest version of the book.
