### ISSUE TITLE
Can grammatical errors be fixed?

### ISSUE THREAD

**Issue by trncb** [open-organization-ambassadors/open-org-leaders-manual#29]
I'm finding grammatical errors in the chapters. Am I able to make changes and create a pull request?

Or, because these chapters are originally blog posts, we can't fix any errors we find?

**Comment by semioticrobotic** [comment]
Thanks for finding those fixes, @trncb! We really appreciate it.

Historically, the easiest approach for readers to take has been to open issues related to the proposed fixes. Those issues should simply detail the page and paragraph locations of the errors, the nature of the errors, and your proposed fixes. When we push new versions of the book, we typically aim to resolve grammatical and typographical issues.

Does that help?

**Comment by trncb** [comment]
It does help, thanks @semioticrobotic . I'd like to directly contribute, if possible. What is your preferred method, since I'm guessing you will be the one approving anything. :)

**Comment by semioticrobotic** [comment]
By "contribute," do you mean "contribute grammatical fixes" or "contribute a new chapter"? I'm happy to discuss either, of course, but I just want to be sure I understand your goals.

- If you'd like to contribute "bug fixes" in the form of spelling/grammar corrections, you can open an issue for those and I'll work with you to address them.

- If you'd like to write something new on open leadership, you can drop me a line at <bbehrens@redhat.com>.

**Comment by trncb** [comment]
My goal is to fix "bugs". I'm nowhere near qualified to actually write new content on open leadership. :)

What I meant by "contribute directly" is that I would like to commit changes to the repo and be noted as a contributor (in the "fixer of bugs" context). But if that isn't possible, I would be happy to work with you as you suggested earlier.

Either way, I still need to log the issues. :)

**Comment by semioticrobotic** [comment]
Gotcha. Thanks, @trncb.

Because the editable source file in ODT, git (and GitHub) can't track changes to it in a transparent and easy way—so receiving reviewing a pull request is difficult because I can't easily compare diffs. That's why, in the past, folks have just logged their proposed changes as issues in the repository and I've addressed them from there (easier to track!), rather than, say, submitting a formal pull request.

I concede that it's not ideal, but so far it's what's worked best.

**Comment by semioticrobotic** [comment]
(Oh, and if getting formally listed as a contributor requires acceptance of a pull request, then I'm sure we can find some way to make it work—I just don't know much about those finer points of GitHub.)

**Comment by trncb** [comment]
Aah, I see. Yes, that makes sense.

Thanks @semioticrobotic . I'll get to logging those issues.

(and as far as I'm aware, a pull request/commit is required)
