### ISSUE TITLE
New chapter: Make your plans and progress open

### ISSUE THREAD

**Issue by jimmysjolund** [open-organization-ambassadors/open-org-leaders-manual#3]
Alternate heading: Visualize your plans

Strategic (and other) plans are often shared only with a certain group and perhaps communicated in an all staff meeting and on the intranet and then forgotten by the masses. By making plans visual and open you will get more collaboration as well as better understanding of the plans and the way forward. I would share examples on how to use visualization methods, techniques, and tools to better collaborate and communicate plans and progress.

**Comment by semioticrobotic** [comment]
I really like this idea, Jimmy, and think it's perfect for this particular edition of the _Leaders Manual_. I'm sure it also ties nicely with your recent research and speaking on this topic, so I'd love to have this opportunity to get some of your recent work on paper and published.
