### ISSUE TITLE
ePub format not listed in repository README

### ISSUE THREAD

**Issue by semioticrobotic** [open-organization-ambassadors/open-org-leaders-manual#30]
The [repository README](https://github.com/open-organization-ambassadors/open-org-leaders-manual/blob/master/README.md) does not explain inclusion of ePub format.

Can @trncb please fix and submit a pull request?

**Comment by trncb** [comment]
I sure can @semioticrobotic .

**Comment by semioticrobotic** [comment]
This is fixed with #31 from @trncb.
