### ISSUE TITLE
Some minor grammatical errors in Part 1 of the book

### ISSUE THREAD

**Issue by trncb** [open-organization-ambassadors/open-org-leaders-manual#32]
Please can the following grammatical be fixed, thank you.

**Page 51, Paragraph 1, Sentence 2**

_From_ 
"Or your could get more creative: "

(remove 'r' from 'your')

_To_
"Or you could get more creative: "

**Page 55, Paragraph 3, Sentence 5**

_From_
"But ultimately whether you do this through a something like a spreadsheet, an intranet site, or a special tool doesn't matter."

(remove duplicate 'a' before 'something', and move 'doesn't matter' to the beginning of the sentence)

_To_
"But, ultimately, it doesn't matter whether you do this through something like a spreadsheet, an intranet site, or a special tool."

**Page 55, Paragraph 4, Sentence 1**

_From_
"A3 reports are the result of a work method or a problem solving approach, one that emerged from Toyota and the Toyota Production System,"

(remove 'a' "," and "one" from sentence)

_To_
"A3 reports are the result of a work method or problem solving approach that emerged from Toyota and the Toyota Production System,"

**Page 57, Paragraph 1, Sentence 1**

_From_
"In his book Toolbox for the Agile Coach: Visualization Examples Jimmy Janlén describes"

(italicize the book title, add "," before author)

_To_
"In his book _Toolbox for the Agile Coach: Visualization Examples_, Jimmy Janlén describes"

**Page 57, Paragraph 2, Sentence 2**

_From_
"The transparency make sure everyone know the status of different improvements,"

(add 's' to 'make' and 'know')

_To_
"The transparency makes sure everyone knows the status of different improvements,"

**Comment by semioticrobotic** [comment]
Really great catches, @trncb. Thanks very much. I am working on these fixes.

**Comment by semioticrobotic** [comment]
These are fixed as part of [commit e4c35f7](https://github.com/open-organization-ambassadors/open-org-leaders-manual/commit/e4c35f7d88c4beb933c23e7577b0e9e28f40b13f).
