### ISSUE TITLE
Minor typos and grammatical errors

### ISSUE THREAD

**Issue by trncb** [open-organization-ambassadors/open-org-leaders-manual#33]
Hi there. I spotted a few minor fixes to be made to the content. If this could be updated, that would be great, thanks.

**Pg 66, last paragraph, sentence 2**
_From_
using "agile" is an explanation
_to_
using "agile" as an explanation

**Pg 73, 1st paragraph, last sentence**
_from_
chose
_to_ 
choose

**Pg 92, 7th paragraph, 1st sentence**
remove repeated word "culture"

**Pg 95, 2nd paragraph, 2nd last sentence**
_from_ 
voice of the community inside company
_to_
voice of the community inside the company

**Pg 96, 3rd paragraph, 4th sentence**
_from_
rules that they undertakes
_to_
rules that they undertake

**Pg 101, 1st paragraph, last sentence**
This one is tricky. I'm not entirely sure what the intention of the sentence. However, here is my interpretation of it.

_From_
In this day and age,thanks to the advent of open source communities research department is opening up to the entire world.
_to_
In this day and age,thanks to the advent of open source communities, research departments are opened up to the entire world.

**Pg 116, 3rd paragraph, last sentence**
remove repeated word "to"

**Pg 125, 1st paragraph, 1st sentence**
_From_
In a scene in from
_to_
In a scene from

**Pg 126, 5th paragraph, 3rd sentence**
_from_
(o how don't they)
_to_
(or how they don't)

**Pg 137, last paragraph, 2nd sentence**
remove repeated word "use"

**Pg 152, 5th paragraph, 1st sentence**
_from_
way to solve multiples issues
_to_
way to solve multiple issues

**Pg 152, 5th paragraph, last sentence**
_from_
clarity of purpose the talents
_to_
clarity of purpose and the talents

**Comment by semioticrobotic** [comment]
Thanks much, @trncb. Great catches (however an embarrassing number of overlooked mistakes on my end). I will get to work on this soon.

**Comment by semioticrobotic** [comment]
Thanks again, @trncb! This is fixed in [v2.1.5](https://github.com/open-organization-ambassadors/open-org-leaders-manual/releases/tag/v2.1.5).
